name: Lint

on: [push]

jobs:
  lint:
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install packages
      run: yarn install --frozen-lockfile
    - name: Run linter
      run: yarn run lint --no-fix
