name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: macOS-latest
    env:
      NODE_ENV: production
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install packages
      run: yarn install --frozen-lockfile
    - name: Run linter
      run: yarn run lint --no-fix

  deploy:
    needs: lint
    runs-on: macOS-latest
    env:
      NODE_ENV: production
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install packages
      run: yarn install --frozen-lockfile
    - name: Install firebase-tools
      run: npm install -g firebase-tools
    - name: Build for production
      run: yarn run build
    - name: Deploy
      run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
